name: Angular CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Cache node modules to improve speed
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Lint the code for static analysis
      - name: Lint code
        run: npm run lint

      # Run unit tests using ChromeHeadless browser
      - name: Run unit tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      # Generate and upload test coverage reports
      - name: Generate coverage report
        run: npm run test -- --watch=false --code-coverage --browsers=ChromeHeadless

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage/

      # Build the project for production
      - name: Build Angular app
        run: npm run build -- --configuration production --base-href "https://sosaidi.github.io/AdvancedMD-frontend/"

      # Archive build artifacts
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/

      # Set git user
      - name: Set git user
        run: |
          git config --global user.email "noreply@github.com"
          git config --global user.name "GitHub Actions Bot"

      # Deploy to GitHub Pages
      - name: Install angular-cli-ghpages
        run: npm install -g angular-cli-ghpages

      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/hospital-management/browser --no-silent
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
