name: SonarCloud Analysis

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      #Start Angular server for SonarCloud
      - name: Start Angular server
        run: npm run start &
        env:
          CI: true

      #Wait for server (Short timeout)
      - name: Wait for server
        run: npx wait-on http://localhost:4200 --timeout 30000

      - name: Run unit tests with coverage
        run: npm run test

      - name: Run SonarCloud Scan
        run: npx sonarqube-scanner \
          -Dsonar.projectKey=sosaidi_AdvancedMD-frontend \
          -Dsonar.organization=sosaidi \
          -Dsonar.sources=src \
          -Dsonar.exclusions=**/node_modules/** \
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
